Repository antvis/wx-f2, pull requests merged in 2020-01, with the labels that each got.

#218 docs: 修改readme
  README.md
Labels: PR: reviewed-changes-requested, documentation

#224 fix: canvas高度继承父容器高度
  src/index.wxss
Labels: PR: unreviewed, bug

#225 chore: release 2.0.1
  package.json
Labels: PR: unreviewed, chore
